// 由 `./kineto sync` 生成，勿手改。素材用 `./kineto asset add <file> --to <video> --as <alias>` 登记。
// 用法：<Img src={staticFile(assets.logo)} />

export const assets = {
  bgMountains: "coffee-life/bgMountains.jpeg",
  bgOcean: "coffee-life/bgOcean.jpeg",
  cargoShip: "coffee-life/cargoShip.jpeg",
  cherryBranch: "coffee-life/cherryBranch.jpeg",
  cupHands: "coffee-life/cupHands.jpeg",
  dryingBeds: "coffee-life/dryingBeds.jpeg",
  fontSerif: "coffee-life/fontSerif.ttf",
  goldenDrum: "coffee-life/goldenDrum.jpeg",
  greenSort: "coffee-life/greenSort.jpeg",
  kettlePour: "coffee-life/kettlePour.jpg",
  musicLongWayHome: "coffee-life/musicLongWayHome.mp3",
  pickBranch: "coffee-life/pickBranch.jpeg",
  sfxBeansPour: "coffee-life/sfxBeansPour.mp3",
  sfxCrackle: "coffee-life/sfxCrackle.wav",
  sfxGrinder: "coffee-life/sfxGrinder.wav",
  sfxPageTurn: "coffee-life/sfxPageTurn.wav",
  sfxWaterPour: "coffee-life/sfxWaterPour.wav",
  vo01: "coffee-life/vo01.wav",
  vo02: "coffee-life/vo02.wav",
  vo03: "coffee-life/vo03.wav",
  vo04: "coffee-life/vo04.wav",
  vo05: "coffee-life/vo05.wav",
  vo06: "coffee-life/vo06.wav",
  vo07: "coffee-life/vo07.wav",
  vo08: "coffee-life/vo08.wav",
  vo09: "coffee-life/vo09.wav",
  vo10: "coffee-life/vo10.wav",
  vo11: "coffee-life/vo11.wav",
  vo12: "coffee-life/vo12.wav",
  vo13: "coffee-life/vo13.wav",
  vo14: "coffee-life/vo14.wav",
  vo15: "coffee-life/vo15.wav",
  vo16: "coffee-life/vo16.wav",
  vo17: "coffee-life/vo17.wav",
  vo18: "coffee-life/vo18.wav",
  worldMap: "coffee-life/worldMap.svg",
} as const;
