// AI 生图：文字描述 → 图片。目前由腾讯混元生图实现；工具按能力命名，换服务商不换命令。
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { setTimeout as sleep } from "node:timers/promises";
import { z } from "zod";
import { KinetoError } from "../../kernel/errors.ts";
import { defineTool } from "../../kernel/tools/define.ts";
import { callTencentCloud } from "../_shared/tencentcloud.ts";

const RESOLUTIONS = ["768:768", "768:1024", "1024:768", "1024:1024", "720:1280", "1280:720", "768:1280", "1280:768"] as const;

const Config = z
  .object({
    secretId: z.string().min(1),
    secretKey: z.string().min(1),
    // 混元生图目前只在广州地域提供
    region: z.string().default("ap-guangzhou"),
    resolution: z.enum(RESOLUTIONS).default("1280:720"),
    // 服务商默认在图上加「AI 生成」标识（国内 AIGC 内容标识要求）；视频里另有标注时可以关掉
    logo: z.boolean().default(true),
    // 让服务商先扩写提示词，出图通常更好；要严格按原文出图时关掉
    revise: z.boolean().default(true),
  })
  .strict();

const POLL_MS = 3000;
const TIMEOUT_MS = 5 * 60_000;

export default defineTool({
  name: "image",
  summary: "Generate an image from a text prompt (Tencent Hunyuan)",
  config: Config,
  args: [{ name: "prompt", description: "What to draw (Chinese works best)" }],
  options: {
    size: { type: "string", value: "w:h", description: `One of ${RESOLUTIONS.join(", ")}` },
    negative: { type: "string", value: "text", description: "What to avoid in the image" },
    style: { type: "string", value: "code", description: "Provider style code" },
    seed: { type: "string", value: "n", description: "Fix the seed to reproduce an image" },
  },
  async run(ctx) {
    const prompt = ctx.args[0]!;
    const resolution = z.enum(RESOLUTIONS).parse(ctx.flags.size ?? ctx.config.resolution);
    const seed = ctx.flags.seed === undefined ? undefined : z.coerce.number().int().parse(ctx.flags.seed);
    const call = <T>(action: string, params: Record<string, unknown>) =>
      callTencentCloud<T>({ credentials: ctx.config, service: "hunyuan", version: "2023-09-01", action, region: ctx.config.region, params });

    const { JobId } = await call<{ JobId: string }>("SubmitHunyuanImageJob", {
      Prompt: prompt,
      Resolution: resolution,
      LogoAdd: ctx.config.logo ? 1 : 0,
      Revise: ctx.config.revise ? 1 : 0,
      ...(typeof ctx.flags.negative === "string" ? { NegativePrompt: ctx.flags.negative } : {}),
      ...(typeof ctx.flags.style === "string" ? { Style: ctx.flags.style } : {}),
      ...(seed === undefined ? {} : { Seed: seed }),
    });

    // 异步任务：1 排队、2 处理中、4 失败、5 完成
    const deadline = Date.now() + TIMEOUT_MS;
    let job: { JobStatusCode: string; JobErrorCode?: string; JobErrorMsg?: string; ResultImage?: string[]; RevisedPrompt?: string[] };
    for (;;) {
      job = await call("QueryHunyuanImageJob", { JobId });
      if (job.JobStatusCode === "5" || job.JobStatusCode === "4") break;
      if (Date.now() > deadline) {
        throw new KinetoError("TOOL_FAILED", `Hunyuan job ${JobId} did not finish in ${TIMEOUT_MS / 60_000} minutes`, { hint: "Retry later." });
      }
      ctx.progress(`generating image (job ${JobId}, status ${job.JobStatusCode})…`);
      await sleep(POLL_MS);
    }
    const url = job.ResultImage?.[0];
    if (job.JobStatusCode === "4" || !url) {
      throw new KinetoError("TOOL_FAILED", `Hunyuan job ${JobId} failed: ${job.JobErrorCode ?? "?"} ${job.JobErrorMsg ?? ""}`.trim(), {
        hint: "Rephrase the prompt (content moderation rejects some prompts) and retry.",
      });
    }

    // 结果链接只保留 1 小时，立刻下载进素材库
    const res = await fetch(url);
    if (!res.ok) throw new KinetoError("TOOL_FAILED", `Cannot download the generated image: HTTP ${res.status}`, { hint: "Retry." });
    const type = res.headers.get("content-type") ?? "";
    const ext = type.includes("png") ? ".png" : type.includes("webp") ? ".webp" : ".jpg";
    const file = path.join(ctx.workDir, `image${ext}`);
    await writeFile(file, Buffer.from(await res.arrayBuffer()));
    const revised = job.RevisedPrompt?.[0];
    return {
      file,
      license: "LicenseRef-TencentCloud-Hunyuan",
      author: "Tencent Hunyuan image generation",
      description:
        `Generated by Tencent Hunyuan (${resolution}${seed === undefined ? "" : `, seed ${seed}`}${ctx.config.logo ? ", AI mark on" : ""}) ` +
        `from prompt: "${prompt}"${revised && revised !== prompt ? `; revised prompt: "${revised.slice(0, 300)}"` : ""}`,
    };
  },
});
