// AI 生图：文字描述 → 图片。目前由腾讯云 TokenHub 上的混元生图 Hy-Image-3.0 实现；
// 工具按能力命名，换服务商、换模型都不换命令。
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { KinetoError } from "../../kernel/errors.ts";
import { defineTool } from "../../kernel/tools/define.ts";
import { checkSize, generateImage, isValidSize, sniffImageExt } from "./tokenhub.ts";

const Config = z
  .object({
    // TokenHub 控制台「API Key 管理」里创建的 key
    apiKey: z.string().min(1),
    // 宽x高，各在 512..2048、面积不超过 1024×1024；默认 16:9 适合当视频画面
    size: z.string().default("1280x720").refine(isValidSize, { message: "size must be WIDTHxHEIGHT, each side 512..2048, at most 1048576 pixels" }),
    // 让服务商先扩写提示词，出图通常更好；要严格按原文出图时关掉
    revise: z.boolean().default(true),
    // 图上的文字水印（最多 16 个字符），比如「AI 生成」
    footnote: z.string().min(1).max(16).optional(),
  })
  .strict();

export default defineTool({
  name: "image",
  summary: "Generate an image from a text prompt (Tencent Hunyuan Hy-Image-3.0 on TokenHub)",
  config: Config,
  args: [{ name: "prompt", description: "What to draw (Chinese and English both work)" }],
  options: {
    size: { type: "string", value: "WxH", description: "e.g. 1280x720, 1024x1024 (each side 512..2048, at most 1024×1024 pixels)" },
    seed: { type: "string", value: "n", description: "Fix the seed to reproduce an image" },
  },
  async run(ctx) {
    const prompt = ctx.args[0]!.trim();
    if (prompt === "") throw new KinetoError("INVALID_ARGUMENT", "The prompt is empty", { hint: "Describe the image to draw." });
    const size = checkSize(String(ctx.flags.size ?? ctx.config.size));
    const seed = ctx.flags.seed === undefined ? undefined : z.coerce.number().int().min(1).max(4294967295).parse(ctx.flags.seed);

    ctx.progress("generating image…");
    const result = await generateImage({
      apiKey: ctx.config.apiKey,
      prompt,
      size,
      revise: ctx.config.revise,
      seed,
      footnote: ctx.config.footnote,
    });

    // 结果是 12 小时有效的临时链接，立刻下载进素材库
    const res = await fetch(result.url, { signal: AbortSignal.timeout(60_000) }).catch((err: unknown) => {
      throw new KinetoError("TOOL_FAILED", `Cannot download the generated image: ${(err as Error).message}`, { hint: "Retry.", cause: err });
    });
    if (!res.ok) throw new KinetoError("TOOL_FAILED", `Cannot download the generated image: HTTP ${res.status}`, { hint: "Retry." });
    const bytes = Buffer.from(
      await res.arrayBuffer().catch((err: unknown) => {
        throw new KinetoError("TOOL_FAILED", `Downloading the generated image was cut off: ${(err as Error).message}`, {
          hint: `Retry; the link stays valid for 12 hours: ${result.url}`,
          cause: err,
        });
      }),
    );
    const file = path.join(ctx.workDir, `image${sniffImageExt(bytes)}`);
    await writeFile(file, bytes);

    const revised = result.revisedPrompt && result.revisedPrompt !== prompt ? `; revised prompt: "${result.revisedPrompt.slice(0, 300)}"` : "";
    return {
      file,
      license: "LicenseRef-TencentCloud-Hunyuan",
      author: "Tencent Hunyuan Hy-Image-3.0 (TokenHub)",
      description:
        `Generated by Tencent Hunyuan Hy-Image-3.0 on TokenHub (${size}${seed === undefined ? "" : `, seed ${seed}`}, ` +
        `request ${result.requestId ?? "?"}) from prompt: "${prompt}"${revised}`,
    };
  },
});
